[package]
name = "fluxion-types"
version.workspace = true
edition = "2024"

[dependencies]
serde.workspace = true
chrono.workspace = true
bevy_ecs.workspace = true
anyhow.workspace = true
fluxion-i18n = { path = "../fluxion-i18n" }
