[package]
name = "fluxion-solax"
version = "0.1.0"
edition = "2024"

[dependencies]
# Local dependencies
fluxion-core = { path = "../fluxion-core" }

# External dependencies
serde = { workspace = true }
serde_json = { workspace = true }
